USE [Teste]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER TRG_QTDE_ALUNOS_MENOS
ON ALUNOS
AFTER DELETE
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE - 1
        WHERE TABELA='Alunos'
    END
GO

CREATE TRIGGER TRG_QTDE_CONG_MENOS
ON CONGREGACOES
AFTER DELETE
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE - 1
        WHERE TABELA='Congregacoes'
    END
GO


CREATE TRIGGER TRG_QTDE_DESIG_MENOS
ON DESIGNACOES
AFTER DELETE
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE - 1
        WHERE TABELA='Designacoes'
    END
GO

CREATE TRIGGER TRG_QTDE_DIRIG_MENOS
ON DIRIGENTES
AFTER DELETE
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE - 1
        WHERE TABELA='Dirigentes'
    END
GO

CREATE TRIGGER TRG_QTDE_DISCFORA_MENOS
ON DISCURSOS_FORA
AFTER DELETE
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE - 1
        WHERE TABELA='Discursos_Fora'
    END
GO

CREATE TRIGGER TRG_QTDE_DISCLOCAIS_MENOS
ON DISCURSOS_LOCAIS
AFTER DELETE
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE - 1
        WHERE TABELA='Discursos_Locais'
    END
GO

CREATE TRIGGER TRG_QTDE_LICOES_MENOS
ON LICOES
AFTER DELETE
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE - 1
        WHERE TABELA='Licoes'
    END
GO

CREATE TRIGGER TRG_QTDE_ORADFORA_MENOS
ON ORADORES_FORA
AFTER DELETE
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE - 1
        WHERE TABELA='Oradores_Fora'
    END
GO

CREATE TRIGGER TRG_QTDE_ORADLOCAIS_MENOS
ON ORADORES_LOCAIS
AFTER DELETE
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE - 1
        WHERE TABELA='Oradores_Locais'
    END
GO

CREATE TRIGGER TRG_QTDE_PUBLIC_MENOS
ON PUBLICADORES
AFTER DELETE
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE - 1
        WHERE TABELA='Publicadores'
    END
GO

CREATE TRIGGER TRG_QTDE_SAIDAS_MENOS
ON SAIDAS
AFTER DELETE
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE - 1
        WHERE TABELA='Saidas'
    END
GO

CREATE TRIGGER TRG_QTDE_TEMAS_MENOS
ON TEMAS
AFTER DELETE
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE - 1
        WHERE TABELA='Temas'
    END
GO

CREATE TRIGGER TRG_QTDE_TERRIT_MENOS
ON TERRITORIOS
AFTER DELETE
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE - 1
        WHERE TABELA='Territorios'
    END
GO
