USE [Teste]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER TRG_QTDE_ALUNOS_MAIS
ON ALUNOS
AFTER INSERT
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE + 1
        WHERE TABELA='Alunos'
    END
GO

CREATE TRIGGER TRG_QTDE_CONG_MAIS
ON CONGREGACOES
AFTER INSERT
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE + 1
        WHERE TABELA='Congregacoes'
    END
GO


CREATE TRIGGER TRG_QTDE_DESIG_MAIS
ON DESIGNACOES
AFTER INSERT
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE + 1
        WHERE TABELA='Designacoes'
    END
GO

CREATE TRIGGER TRG_QTDE_DIRIG_MAIS
ON DIRIGENTES
AFTER INSERT
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE + 1
        WHERE TABELA='Dirigentes'
    END
GO

CREATE TRIGGER TRG_QTDE_DISCFORA_MAIS
ON DISCURSOS_FORA
AFTER INSERT
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE + 1
        WHERE TABELA='Discursos_Fora'
    END
GO

CREATE TRIGGER TRG_QTDE_DISCLOCAIS_MAIS
ON DISCURSOS_LOCAIS
AFTER INSERT
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE + 1
        WHERE TABELA='Discursos_Locais'
    END
GO

CREATE TRIGGER TRG_QTDE_LICOES_MAIS
ON LICOES
AFTER INSERT
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE + 1
        WHERE TABELA='Licoes'
    END
GO

CREATE TRIGGER TRG_QTDE_ORADFORA_MAIS
ON ORADORES_FORA
AFTER INSERT
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE + 1
        WHERE TABELA='Oradores_Fora'
    END
GO

CREATE TRIGGER TRG_QTDE_ORADLOCAIS_MAIS
ON ORADORES_LOCAIS
AFTER INSERT
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE + 1
        WHERE TABELA='Oradores_Locais'
    END
GO

CREATE TRIGGER TRG_QTDE_PUBLIC_MAIS
ON PUBLICADORES
AFTER INSERT
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE + 1
        WHERE TABELA='Publicadores'
    END
GO

CREATE TRIGGER TRG_QTDE_SAIDAS_MAIS
ON SAIDAS
AFTER INSERT
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE + 1
        WHERE TABELA='Saidas'
    END
GO

CREATE TRIGGER TRG_QTDE_TEMAS_MAIS
ON TEMAS
AFTER INSERT
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE + 1
        WHERE TABELA='Temas'
    END
GO

CREATE TRIGGER TRG_QTDE_TERRIT_MAIS
ON TERRITORIOS
AFTER INSERT
AS
    BEGIN
        UPDATE INFO_TABLES
        SET QTDE = QTDE + 1
        WHERE TABELA='Territorios'
    END
GO
